"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ui.py']
DATA_FILES = ['resources/icon.png']
OPTIONS = {
	'argv_emulation': True, 
	'plist': {
		'LSUIElement': True,
	},
	'includes': ['harmony'],
	'iconfile': 'resources/icon.icns'
}

setup(
    name='Harmenubar',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
